version: '3'

services:
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # On Production Mode Change Db User And Password
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p 5432
  web:
    build:
      context: .
      dockerfile: django.dockerfile
    command: bash start.sh
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    links:
      - db
volumes:
  pgdata: