# Generated by Django 4.2.5 on 2023-09-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletcurrency",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
                verbose_name="Wallet",
            ),
        ),
    ]
