# Generated by Django 4.2.5 on 2023-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletcurrency",
            name="quantity",
            field=models.BigIntegerField(verbose_name="quantity"),
        ),
    ]
